### ISSUE TITLE
Functionality has stopped

### ISSUE THREAD

**Issue by dy1b0t** [pinetwork-js/pi-browser-extension#3]
This browser extension has seemed to stop working roughly 2 months ago (Aug, 2023) on both chrome and Firefox. I’ve tried uninstalling/reinstalling etc. It will allow me to login, but it will not allow me to open any extensions with browser=pi:// including the welcome home page. It did previously work swimmingly up until this point and this nonfunctionality has been verified by my partner also. Please advise.

**Comment by b-derouet** [comment]
This issue has been fixed!
